"""Domain entities for trading recommendations."""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import UTC, datetime

from domain.enums import MarketRegime, StrategyType, TradingAction


@dataclass(frozen=True)
class Candle:
    """Persistable OHLCV candle from a market data source."""

    symbol: str
    timeframe: str
    timestamp: datetime
    open: float
    high: float
    low: float
    close: float
    volume: float


@dataclass(frozen=True)
class OHLCVBar:
    """Single OHLCV candle used by the analysis pipeline."""

    timestamp: datetime
    open: float
    high: float
    low: float
    close: float
    volume: float


@dataclass(frozen=True)
class MarketSnapshot:
    """Minimal market state required for a recommendation."""

    symbol: str
    close_price: float
    timestamp: datetime = field(default_factory=lambda: datetime.now(UTC))


@dataclass(frozen=True)
class SetupRecommendation:
    """Trading setup recommendation generated by the system."""

    symbol: str
    action: TradingAction
    confidence: float
    rationale: str
    created_at: datetime = field(default_factory=lambda: datetime.now(UTC))

    def to_display_text(self) -> str:
        """Format the recommendation for a local UI."""
        return (
            f"{self.symbol}: {self.action.value} "
            f"(confidence={self.confidence:.2f}) - {self.rationale}"
        )


@dataclass(frozen=True)
class RiskPlan:
    """Risk plan for a candidate setup."""

    action: TradingAction
    entry: float
    stop_loss: float
    take_profit: float
    risk_reward: float
    position_size: float


@dataclass(frozen=True)
class TradeSetup:
    """Complete output produced by the trading orchestrator."""

    symbol: str
    action: TradingAction
    confidence: float
    regime: MarketRegime | None
    strategy: StrategyType | None
    probabilities: dict[TradingAction, float]
    risk_plan: RiskPlan | None
    reasons: list[str]
    explanation: str
    created_at: datetime = field(default_factory=lambda: datetime.now(UTC))

    def to_display_text(self) -> str:
        """Format the trade setup for a local UI."""
        strategy = self.strategy.value if self.strategy else "No strategy"
        regime = self.regime.value if self.regime else "UNKNOWN"
        return (
            f"{self.symbol}: {self.action.value} "
            f"(confidence={self.confidence:.2f}, regime={regime}, strategy={strategy})"
        )
